include(ProcessorCount)
ProcessorCount(N)
if(NOT N EQUAL 0)
 set(CTEST_BUILD_FLAGS -j${N})
 set(ctest_test_args ${ctest_test_args} PARALLEL_LEVEL ${N})
 message(STATUS "Number of Processors detected: ${N}")
endif()
